"""icecat_index table migration recreated

Revision ID: 0ecdf6c00ca5
Revises: 602bae9339ef
Create Date: 2022-06-20 12:18:30.254043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecdf6c00ca5'
down_revision = '602bae9339ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_index',
    sa.Column('ean', sa.String(length=13), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ean')
    )
    op.alter_column('PIM_query20_5', 'Variant_product',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('PIM_query29', 'Variant_product',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PIM_query29', 'Variant_product',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('PIM_query20_5', 'Variant_product',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_table('icecat_index')
    # ### end Alembic commands ###
