"""drop icecat_ean, icecat_sku, add icecat_index

Revision ID: 13a59e86b104
Revises: 2af21c22f77e
Create Date: 2022-06-10 08:47:08.461214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a59e86b104'
down_revision = '2af21c22f77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icecat_sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_sku',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='icecat_sku_pkey')
    )
    # ### end Alembic commands ###
