"""drop icecat_ean, icecat_sku, add icecat_index

Revision ID: 2af21c22f77e
Revises: e8d0c65d109b
Create Date: 2022-06-10 08:29:57.006840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af21c22f77e'
down_revision = 'e8d0c65d109b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_index',
    sa.Column('ean', sa.String(length=13), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ean')
    )
    op.drop_table('icecat_ean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_ean',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ean', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ean', name='icecat_ean_pkey')
    )
    op.drop_table('icecat_index')
    # ### end Alembic commands ###
