"""pim data format updated acc. to that of dumps

Revision ID: 602bae9339ef
Revises: 13a59e86b104
Create Date: 2022-06-17 11:04:24.272620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602bae9339ef'
down_revision = '78c42e1e8f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_PIM_query20_5_EAN'), 'PIM_query20_5', ['EAN'], unique=False)
    op.drop_column('PIM_query20_5', 'id')
    op.drop_column('PIM_query20_5', 'AM_SystemModified')
    op.drop_column('PIM_query20_5', 'AM_ExcelFileWithPath')
    op.drop_column('PIM_query20_5', 'AM_SystemCreated')
    op.alter_column('PIM_query29', 'Value_language',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    op.create_index(op.f('ix_PIM_query29_Variant_product'), 'PIM_query29', ['Variant_product'], unique=False)
    op.drop_column('PIM_query29', 'Value_position')
    op.drop_column('PIM_query29', 'AM_SystemModified')
    op.drop_column('PIM_query29', 'AM_ExcelFileWithPath')
    op.drop_column('PIM_query29', 'AM_SystemCreated')
    op.drop_column('PIM_query29', 'lfd_nr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PIM_query29', sa.Column('lfd_nr', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('PIM_query29', sa.Column('AM_SystemCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('PIM_query29', sa.Column('AM_ExcelFileWithPath', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('PIM_query29', sa.Column('AM_SystemModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('PIM_query29', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PIM_query29_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('PIM_query29', sa.Column('Value_position', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_PIM_query29_Variant_product'), table_name='PIM_query29')
    op.alter_column('PIM_query29', 'Value_language',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.add_column('PIM_query20_5', sa.Column('AM_SystemCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('PIM_query20_5', sa.Column('AM_ExcelFileWithPath', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('PIM_query20_5', sa.Column('AM_SystemModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_PIM_query20_5_EAN'), table_name='PIM_query20_5')
    # ### end Alembic commands ###
