"""pim2ean, q205 and q29 views of bdx added as ref tables

Revision ID: 78c42e1e8f59
Revises: 
Create Date: 2022-04-14 14:44:45.153121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c42e1e8f59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PIM_aktuell_Query20_5_DE_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Variant_product', sa.String(length=15), nullable=True),
    sa.Column('Base_product', sa.String(length=9), nullable=True),
    sa.Column('EAN', sa.String(length=13), nullable=True),
    sa.Column('Product_name', sa.String(length=400), nullable=True),
    sa.Column('SAP_name', sa.String(length=120), nullable=True),
    sa.Column('Mandators', sa.String(length=90), nullable=True),
    sa.Column('Suppliers', sa.String(length=350), nullable=True),
    sa.Column('Main_material_group', sa.String(length=1), nullable=True),
    sa.Column('KSP', sa.String(length=2), nullable=True),
    sa.Column('Material_group_subgroup', sa.String(length=5), nullable=True),
    sa.Column('Material_group_node', sa.String(length=5), nullable=True),
    sa.Column('Material_group', sa.String(length=75), nullable=True),
    sa.Column('SAP_status', sa.String(length=13), nullable=True),
    sa.Column('Approval', sa.String(length=12), nullable=True),
    sa.Column('Status_data_maintenance', sa.String(length=35), nullable=True),
    sa.Column('Flag_status', sa.String(length=12), nullable=True),
    sa.Column('Online_reservation', sa.String(length=3), nullable=True),
    sa.Column('Maintenance_classification', sa.String(length=2), nullable=True),
    sa.Column('Processed_by_tool', sa.String(length=5), nullable=True),
    sa.Column('Initial_responsibility', sa.String(length=20), nullable=True),
    sa.Column('General_responsibility', sa.String(length=20), nullable=True),
    sa.Column('Private_brand___brand', sa.String(length=50), nullable=True),
    sa.Column('Product_line', sa.String(length=50), nullable=True),
    sa.Column('Product_name_category', sa.String(length=50), nullable=True),
    sa.Column('Type_designation', sa.String(length=80), nullable=True),
    sa.Column('Description', sa.String(length=10000), nullable=True),
    sa.Column('USP_1', sa.String(length=110), nullable=True),
    sa.Column('USP_2', sa.String(length=110), nullable=True),
    sa.Column('USP_3', sa.String(length=110), nullable=True),
    sa.Column('USP_4', sa.String(length=110), nullable=True),
    sa.Column('USP_5', sa.String(length=110), nullable=True),
    sa.Column('Name_attributes', sa.String(length=125), nullable=True),
    sa.Column('Primary_frontend_category', sa.String(length=8), nullable=True),
    sa.Column('Secondary_frontend_categories', sa.String(length=110), nullable=True),
    sa.Column('Count_available_images', sa.String(length=5), nullable=True),
    sa.Column('Count_active_images', sa.String(length=5), nullable=True),
    sa.Column('URL_main_image', sa.String(length=100), nullable=True),
    sa.Column('AM_SystemCreated', sa.DateTime(), nullable=True),
    sa.Column('AM_SystemModified', sa.DateTime(), nullable=True),
    sa.Column('AM_ExcelFileWithPath', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PIM_akutell_Query29_DE_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Material_group', sa.String(length=60), nullable=True),
    sa.Column('Variant_product', sa.String(length=60), nullable=True),
    sa.Column('Mandators', sa.String(length=33), nullable=True),
    sa.Column('SAP_name', sa.String(length=75), nullable=True),
    sa.Column('Product_name_category', sa.String(length=110), nullable=True),
    sa.Column('Classifying_category', sa.String(length=80), nullable=True),
    sa.Column('Attribute_identifier', sa.String(length=80), nullable=True),
    sa.Column('Attribute_name', sa.String(length=80), nullable=True),
    sa.Column('Attribute_type', sa.String(length=9), nullable=True),
    sa.Column('Value_identifier', sa.String(length=300), nullable=True),
    sa.Column('Value_name', sa.String(length=300), nullable=True),
    sa.Column('Value_unit', sa.String(length=60), nullable=True),
    sa.Column('Value_position', sa.String(length=4), nullable=True),
    sa.Column('Value_language', sa.String(length=35), nullable=True),
    sa.Column('lfd_nr', sa.Integer(), nullable=True),
    sa.Column('AM_SystemCreated', sa.DateTime(), nullable=True),
    sa.Column('AM_SystemModified', sa.DateTime(), nullable=True),
    sa.Column('AM_ExcelFileWithPath', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pim_ean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_product', sa.String(length=24), nullable=True),
    sa.Column('base_product', sa.String(length=24), nullable=True),
    sa.Column('material_group', sa.String(length=24), nullable=True),
    sa.Column('ean', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pim_ean')
    op.drop_table('PIM_akutell_Query29_DE_view')
    op.drop_table('PIM_aktuell_Query20_5_DE_view')
    # ### end Alembic commands ###
