"""drop icecat_index, add icecat_sku, icecat_ean table

Revision ID: e8d0c65d109b
Revises: ad2e0636d9c8
Create Date: 2022-06-09 09:35:27.531662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d0c65d109b'
down_revision = 'ad2e0636d9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_ean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('ean')
    )
    op.create_table('icecat_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('icecat_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_index',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ean', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='icecat_index_pkey')
    )
    op.drop_table('icecat_sku')
    op.drop_table('icecat_ean')
    # ### end Alembic commands ###
