"""create ean2pim refs table

Revision ID: f3f8a577b755
Revises: 
Create Date: 2021-11-04 10:42:25.760880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f8a577b755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pim_ean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pim_ean',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_product', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('base_product', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('material_group', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('ean', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pim_ean_pkey')
    )
    # ### end Alembic commands ###
